### ISSUE TITLE
Proyecto Final-Pulsador

### ISSUE THREAD

**Issue by Arlet04** [SistemasTecTlaxiaco/proyecto-pulsador-equipo-jeanette-arlet-salazar-nicolas#1]
[Proyecto-pulsador.pdf](https://github.com/SistemasTecTlaxiaco/proyecto-pulsador-equipo-jeanette-arlet-salazar-nicolas/files/7819335/Proyecto-pulsador.pdf)

**Comment by josealfredo79** [comment]
Falto el circuito físico

**Comment by josealfredo79** [comment]
Revisado
